# Generated by Django 4.1.6 on 2023-02-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(max_length=100)),
                ('website_name', models.CharField(max_length=100)),
                ('objectives', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='website_logos/%Y/%m/%d/')),
                ('bg_color', models.CharField(help_text='color_code: #000000', max_length=7, null=True)),
                ('font_color', models.CharField(help_text='color_code: #000000', max_length=7, null=True)),
                ('font_url', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('github_link', models.CharField(max_length=200, null=True)),
                ('linkedin_link', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_website', 'Can view website information')],
            },
        ),
    ]
