# Generated by Django 4.1.6 on 2023-02-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_technologies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RemoveField(
            model_name='educationinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='educationinformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
