# Generated by Django 4.1.4 on 2022-12-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_attribute_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_attribute', to='website.attribute'),
            preserve_default=False,
        ),
    ]
