# Generated by Django 4.1.4 on 2022-12-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_musician_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
